{% set version = '3043.102' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-timedate
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/timeDate_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/timeDate/timeDate_{{ version }}.tar.gz
  sha256: 377cba03cddab8c6992e31d0683c1db3a73afa9834eee3e95b3b0723f02d7473

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  noarch: generic

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: date, RUnit
requirements:
  build:
    - {{posix}}zip               # [win]

  host:
    - r-base

  run:
    - r-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('timeDate')"           # [not win]
    - "\"%R%\" -e \"library('timeDate')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://www.rmetrics.org
  license: GPL (>= 2)
  summary: The 'timeDate' class fulfils the conventions of the ISO 8601  standard as well as
    of the ANSI C and POSIX standards. Beyond these standards it provides the "Financial
    Center" concept which allows to handle data records collected in different time  zones
    and mix them up to have always the proper time stamps with  respect to your personal
    financial center, or alternatively to the GMT reference time. It can thus also handle
    time stamps from historical  data records from the same time zone, even if the financial  centers
    changed day light saving times at different calendar dates.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - croth1
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: timeDate
# Title: Rmetrics - Chronological and Calendar Objects
# Date: 2018-02-21
# Version: 3043.102
# Author: Diethelm Wuertz [aut], Tobias Setz [cre], Yohan Chalabi [ctb], Martin Maechler [ctb], Joe W. Byers [ctb]
# Maintainer: Tobias Setz <tobias.setz@live.com>
# Description: The 'timeDate' class fulfils the conventions of the ISO 8601  standard as well as of the ANSI C and POSIX standards. Beyond these standards it provides the "Financial Center" concept which allows to handle data records collected in different time  zones and mix them up to have always the proper time stamps with  respect to your personal financial center, or alternatively to the GMT reference time. It can thus also handle time stamps from historical  data records from the same time zone, even if the financial  centers changed day light saving times at different calendar dates.
# Depends: R (>= 2.15.1), graphics, utils, stats, methods
# Suggests: date, RUnit
# LazyData: yes
# License: GPL (>= 2)
# URL: https://www.rmetrics.org
# NeedsCompilation: no
# Packaged: 2018-02-21 13:20:37 UTC; Tobias Setz
# Repository: CRAN
# Date/Publication: 2018-02-21 23:23:49 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
