travis:
  secure:
    BINSTAR_TOKEN: IthKjFE9MKs4QtSnEBJ3RbR0df9biORTwYv81r+UOkBtT7suSRV+c7VIsNzQ3l8iqYz+fvcUPzNqQfHry21lACAa72kJWibnUeddOyu7XLcM1LoouCwrLTBSf3R0tFDvoNTIJYYeE9vAjxxFkPsckB6OHZyCl6gDKmBfmtKPFq7wnsNWtk8GAhVQBgPkAE/BQwUVi1NQ3tl+Q6g2XMnMgbN8Y9J4aBPvMq2nSDVp+Ow0Ofyy5SBCPBveNgai2PP6dXHMVzfYJqfr4L1ypxS7ok0trBkBtD1RW9oP2U2dOhM1S+/qGEhGPvoA6OdWA7hWwRX5XP+Xhos9wMOPBkrbvcxZNvxQRq2ndPV4V+1slXegwtJbrSdjti8FfqAYT1R0qPtn1SU0wcL8BEePDnT0uAEDovZlYpjeLIKN5BJ8VMZYL8JSyI6GUKvprkOYl2FcP48BEoYs6RAYULrl2FGdLDTNm7V7855M0LzMsw6tedbNM+AEvWHtM5dGRiZaYMjifnLgNordP+B0r4H9GPBZTIBDnPj8xgHjdOqzD2G8/96EkiizFZwSMG4ghpjPsLPg75j842LPLT4KAMSaFgAPmhAM1TncW88lNwgaraocFhaFY6cvXc8ZjX8/sewQ2qz3y84piyXsUFEILAxdNozXXFZu2JMV2Zisbq4jj0McnJI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
