travis:
  secure:
    BINSTAR_TOKEN: Mg+Z6tVW3eZGqHCa8M3DIqLRBOOqgfbKqyeMgDL5n44sjtiOSP3j3wiJG9iYXJmPd6HnYyF0qmdQiJimLf7nFexKQqZDesg7W9y6gicDxRgLSVWsWmEnra6KGk+T2cCdooBI52EvmqZkEhCFyoJ0kDZR5KxJRJZ/BDeTeEyf+cfrzoaT1POrUT8td8I/04dWS/lUYqKLS+L0dkl0OOyfPflkKKN+DQrdV8EBGkZxe7OnDlpFDpZy2tnhdpe0mwBzPmugmRWn89fp8DH9kv3QTlpthkPFCkhK3R/y4imRxLV7MrYoONi0vo8UM68YZoeGlSS4mdyraG1Owy0ND3bxqjVbH/jaC+bB5mYp+/4f2LaRpmrz5rCyRUjZcFRLAQ+klyPau5GKTXin2aAMgwm9PccdpyDejTXi2jk3R2jnZJEs3d32UendoxsCiZWivvt9vJamh3VVKlWDSrIszWEsIN/NxaNne6FlNUs3YDNGt0sW9ARcGv/O45Djiu1LEKw+tdbwNyhOhTsxcU8cklPSQwsPx8rmgwARGfV8YwQNbi04LSrMduHuU13DLv0M1fUk4rRz9NxyWc0CVGPawUDPAUsuBKgd1e8mJO4PWiEyQGLUR86MCaTeiqp4tssx/pzdLZakPLqBL5DKWop/NkAkXQISQp3Qtep1Ko3fNbti17o=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
